### ISSUE TITLE
How to reproduce data.csv?

### ISSUE THREAD

**Issue by mraashish** [emara-geek/dlib-model-evaluation#2]
I am trying to reproduce the embeddings using face_recognition library of dlib but so far my embeddings only gve about 72% accuracy. 
What are the preprocessing steps you did to acquire the said embeddings in data.csv?

**Comment by tahaemara** [comment]
Just use this code https://github.com/davisking/dlib/blob/master/examples/dnn_face_recognition_ex.cpp
